apply search field
devhausleipzigacademy/camp12-midterm pull request #22
Opened 2024-07-01 12:17 UTC by Hydrateurself

## Checklist

Confirm you have completed the following actions prior to submitting this PR.

- [ ] There is an existing issue report for this PR.
- [ ] I have created a feature branch.
- [ ] My changes have been committed.
- [ ] I have pushed my changes to the branch.

## Title

_Give your PR a short title summarising the patch, bug fix or feature._

## Description

_Ensure the PR description clearly describes the problem and solution and provide as much relevant information as possible._

## Issue Resolution

_Tell us which issue this PR fixes._

Closes #5

2024-07-01 12:57 UTC, dnmct requested changes

2024-07-01 12:57 UTC, dnmct commented on src/components/input.tsx
> +                                 className="bg-transparent w-[335px] h-[48px] rounded-full placeholder: font-medium placeholder: font-inter placeholder: text-sm placeholder: leading-4 placeholder: pl
some of the classes are not applied because you have spaces in there

2024-07-01 12:57 UTC, dnmct commented on src/components/input.tsx
pls always format your files before pushing

2024-07-01 12:57 UTC, dnmct commented on src/components/input.tsx
> +    icon: IconType,
the icon prop is not used

2024-07-01 12:57 UTC, dnmct commented on src/components/input.tsx
> +export const InputFields = ({ placeholder,icon}: Props) => {
maybe just call it Input, every instance of a component is a single thing

2024-07-01 12:57 UTC, dnmct commented on src/components/input.tsx
> +                    <IoIosSearch className="text-white-dimmed h-5" />
use size-5 instead of h-5, to make sure aspect ratio is always square

2024-07-01 12:57 UTC, dnmct commented on src/components/input.tsx
> +            <label className="flex items-center w-[335px] h-[48px] rounded-full bg-dark-light border-2 border-dark-light focus-within:border-white-dimmed-heavy ">
don't use arbitrary values for height and width work with padding instead

2024-07-02 09:15 UTC, Hydrateurself commented
fixed the issues ready to merge?

2024-07-02 09:39 UTC, dnmct approved these changes

2024-07-02 09:40 UTC, merged