created Section Title Component
devhausleipzigacademy/camp12-midterm pull request #29
Opened 2024-07-01 14:23 UTC by Fredmpk

## Checklist

Confirm you have completed the following actions prior to submitting this PR.

- [x] There is an existing issue report for this PR.
- [x] I have created a feature branch.
- [x] My changes have been committed.
- [x] I have pushed my changes to the branch.

## Title

created Section Title Component

## Description

I created a component for the section title, it's possible to pass a text and show or hide the See All - link through the props.

2024-07-02 12:39 UTC, dnmct requested changes, later dismissed

2024-07-02 12:39 UTC, dnmct commented on src/components/section-title.tsx
> +      <span className="text-white">{text}</span>
Font should be medium weight

2024-07-02 12:39 UTC, dnmct commented on src/components/section-title.tsx
> +            <span>See All</span>
Text is too big

2024-07-02 12:39 UTC, dnmct commented on src/components/section-title.tsx
> +            <svg
Use a heroicons arrow

2024-07-02 12:39 UTC, dnmct commented on src/components/section-title.tsx
> +          <div className="flex">
gap between text and arrow is missing

2024-07-02 12:39 UTC, dnmct commented on src/components/section-title.tsx
> +    <div className="flex justify-between">
also align on the vertical axis here

2024-07-03 12:19 UTC, louziferr approved these changes
good job !

2024-07-03 12:51 UTC, merged